weixin-vue-test:
  cache:
    untracked: true
    paths:
    - node_modules/
  tags:
    - weixin-jq-tag
  script:
    - cnpm install
    - cnpm run test

  only:
    - /^.*test$/
  after_script:
    - scp -r dist/* web@47.93.35.76:/home/web/webhive/nginx/vue/dist
    - scp -r html/* web@47.93.35.76:/home/web/webhive/nginx/vue
    - scp -r html/* web@47.93.35.76:/home/web/webhive/nginx/jq

weixin-vue-build:
  cache:
    untracked: true
    paths:
    - node_modules/
  tags:
    - weixin-jq-tag
  script:
    - cnpm install
    - cnpm run build

  only:
    - build
  after_script:
    - scp -r dist/* web@47.93.35.76:/home/web/wechat/vue/dist
    - scp -r html/* web@47.93.35.76:/home/web/wechat/vue
    - scp -r html/* web@47.93.35.76:/home/web/wechat/jq
